apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: nodeapp-service
spec:
  ports:
  - name: server
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapp
  type: NodePort