apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb-svc
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mariadb
  clusterIP: None