apiVersion: v1
kind: ConfigMap
metadata:
  name: html-cm
data:
  index.html: |-
    <!doctype html>
    <html>
    <head>
      <title>Hello world!</title>
    </head>
    <body>
      <p>Hello from the custom server</p>
    </body>
    </html>
  custom_404.html: |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>404 Not Found</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                text-align: center;
                padding: 50px;
            }
            h1 {
                font-size: 50px;
            }
            p {
                font-size: 20px;
            }
        </style>
    </head>
    <body>
        <h1>404 Not Found</h1>
        <p>Sorry, the page you are looking for does not exist.</p>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-cm
data:
  nginx.conf: |
    events { }

    http {
        server {
            listen 80;

            root /usr/share/nginx/html;
            index index.html;

            error_page 404 /custom_404.html;
            
            location / {
                try_files $uri $uri/ =404;
            }
        }
    }
