apiVersion: v1
kind: Service
metadata:
  labels:
    app: custom-server
  name: custom-server-svc
spec:
  ports:
  - name: server
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: custom-server
  type: NodePort