apiVersion: v1
kind: Service
metadata:
  labels:
    app: great-service
  name: great-service-svc
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: great-service
  type: NodePort